### ISSUE TITLE
TLE7209 needs larger vias behind chip to allow soldering

### ISSUE THREAD

**Issue by rusefi** [rusefi/hw_modular#20]
TLE7209 vias under the chip do not currently allow to fill those using solder wire from behind

please use 1.5mm diameter vias

**Comment by mck1117** [comment]
solder paste?

**Comment by rusefi** [comment]
solder paste is great. larger vias allow solder wire as an extra option

**Comment by hotbrilliant** [comment]
Sized up to 1mm
