### ISSUE TITLE
CJ125 missing a trace VCCsomething

### ISSUE THREAD

**Issue by rusefi** [rusefi/hw_modular#37]
in order to get board alive we had to jump a not connected pin to +5v I believe

**Comment by rusefi** [comment]
![img_20200502_205805](https://user-images.githubusercontent.com/7377949/82133059-fa737700-97b4-11ea-9380-30233021fe59.jpg)

**Comment by rusefi** [comment]
"VCCS and VCSS are short-circuited on the IC." looks like not the case on this package

**Comment by jharvey** [comment]
R0.1.1 adds this 5V wire. Sorry I forgot to link to this issue when I committed and pushed.

**Comment by jharvey** [comment]
I believe this can be closed.
